stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - apk add curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=master "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'